// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | HomeInstagramSlice
  | HomeTravelCarouselSlice
  | HomeCarouselSlice
  | HomeDescriptionSlice
  | HeroSlice
  | NavigationSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cta field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * background field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background: prismic.LinkToMediaField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *HomeCarousel → Default → Primary → carousel*
 */
export interface HomeCarouselSliceDefaultPrimaryCarouselItem {
  /**
   * image field in *HomeCarousel → Default → Primary → carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeCarousel → Default → Primary*
 */
export interface HomeCarouselSliceDefaultPrimary {
  /**
   * title field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * cta field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * carousel field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<HomeCarouselSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for HomeCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeCarousel*
 */
type HomeCarouselSliceVariation = HomeCarouselSliceDefault;

/**
 * HomeCarousel Shared Slice
 *
 * - **API ID**: `home_carousel`
 * - **Description**: HomeCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeCarouselSlice = prismic.SharedSlice<
  "home_carousel",
  HomeCarouselSliceVariation
>;

/**
 * Item in *HomeDescription → Default → Primary → products*
 */
export interface HomeDescriptionSliceDefaultPrimaryProductsItem {
  /**
   * title field in *HomeDescription → Default → Primary → products*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cta field in *HomeDescription → Default → Primary → products*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[].cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * background field in *HomeDescription → Default → Primary → products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[].background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeDescription → Default → Primary*
 */
export interface HomeDescriptionSliceDefaultPrimary {
  /**
   * title field in *HomeDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *HomeDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * products field in *HomeDescription → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  products: prismic.GroupField<
    Simplify<HomeDescriptionSliceDefaultPrimaryProductsItem>
  >;
}

/**
 * Default variation for HomeDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeDescription*
 */
type HomeDescriptionSliceVariation = HomeDescriptionSliceDefault;

/**
 * HomeDescription Shared Slice
 *
 * - **API ID**: `home_description`
 * - **Description**: HomeDescription
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeDescriptionSlice = prismic.SharedSlice<
  "home_description",
  HomeDescriptionSliceVariation
>;

/**
 * Item in *HomeInstagram → Default → Primary → instagram*
 */
export interface HomeInstagramSliceDefaultPrimaryInstagramItem {
  /**
   * instagram post code field in *HomeInstagram → Default → Primary → instagram*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.instagram[].instagram_post_code
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram_post_code: prismic.KeyTextField;
}

/**
 * Item in *HomeInstagram → Default → Primary → social media*
 */
export interface HomeInstagramSliceDefaultPrimarySocialMediaItem {
  /**
   * logo field in *HomeInstagram → Default → Primary → social media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.social_media[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * link field in *HomeInstagram → Default → Primary → social media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.social_media[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *HomeInstagram → Default → Primary*
 */
export interface HomeInstagramSliceDefaultPrimary {
  /**
   * title field in *HomeInstagram → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * instagram field in *HomeInstagram → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.instagram[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  instagram: prismic.GroupField<
    Simplify<HomeInstagramSliceDefaultPrimaryInstagramItem>
  >;

  /**
   * social media field in *HomeInstagram → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.social_media[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<
    Simplify<HomeInstagramSliceDefaultPrimarySocialMediaItem>
  >;
}

/**
 * Default variation for HomeInstagram Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeInstagramSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeInstagramSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeInstagram*
 */
type HomeInstagramSliceVariation = HomeInstagramSliceDefault;

/**
 * HomeInstagram Shared Slice
 *
 * - **API ID**: `home_instagram`
 * - **Description**: HomeInstagram
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeInstagramSlice = prismic.SharedSlice<
  "home_instagram",
  HomeInstagramSliceVariation
>;

/**
 * Item in *HomeTravelCarousel → Default → Primary → carousel*
 */
export interface HomeTravelCarouselSliceDefaultPrimaryCarouselItem {
  /**
   * image field in *HomeTravelCarousel → Default → Primary → carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeTravelCarousel → Default → Primary*
 */
export interface HomeTravelCarouselSliceDefaultPrimary {
  /**
   * title field in *HomeTravelCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cta field in *HomeTravelCarousel → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * carousel field in *HomeTravelCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<HomeTravelCarouselSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for HomeTravelCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeTravelCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeTravelCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeTravelCarousel*
 */
type HomeTravelCarouselSliceVariation = HomeTravelCarouselSliceDefault;

/**
 * HomeTravelCarousel Shared Slice
 *
 * - **API ID**: `home_travel_carousel`
 * - **Description**: HomeTravelCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeTravelCarouselSlice = prismic.SharedSlice<
  "home_travel_carousel",
  HomeTravelCarouselSliceVariation
>;

/**
 * Item in *Navigation → Default → Primary → navigation item*
 */
export interface NavigationSliceDefaultPrimaryNavigationItemItem {
  /**
   * image field in *Navigation → Default → Primary → navigation item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.navigation_item[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *Navigation → Default → Primary → navigation item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.navigation_item[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Navigation → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
  /**
   * navigation item field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.navigation_item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_item: prismic.GroupField<
    Simplify<NavigationSliceDefaultPrimaryNavigationItemItem>
  >;

  /**
   * mobile cta field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.mobile_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mobile_cta: prismic.LinkField;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault;

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlice = prismic.SharedSlice<
  "navigation",
  NavigationSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HomeCarouselSlice,
      HomeCarouselSliceDefaultPrimaryCarouselItem,
      HomeCarouselSliceDefaultPrimary,
      HomeCarouselSliceVariation,
      HomeCarouselSliceDefault,
      HomeDescriptionSlice,
      HomeDescriptionSliceDefaultPrimaryProductsItem,
      HomeDescriptionSliceDefaultPrimary,
      HomeDescriptionSliceVariation,
      HomeDescriptionSliceDefault,
      HomeInstagramSlice,
      HomeInstagramSliceDefaultPrimaryInstagramItem,
      HomeInstagramSliceDefaultPrimarySocialMediaItem,
      HomeInstagramSliceDefaultPrimary,
      HomeInstagramSliceVariation,
      HomeInstagramSliceDefault,
      HomeTravelCarouselSlice,
      HomeTravelCarouselSliceDefaultPrimaryCarouselItem,
      HomeTravelCarouselSliceDefaultPrimary,
      HomeTravelCarouselSliceVariation,
      HomeTravelCarouselSliceDefault,
      NavigationSlice,
      NavigationSliceDefaultPrimaryNavigationItemItem,
      NavigationSliceDefaultPrimary,
      NavigationSliceVariation,
      NavigationSliceDefault,
    };
  }
}
