// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | ContactFormSlice
  | AboutUsPressSlice
  | AboutUsTestimonialsSlice
  | AboutUsValuesSlice
  | AboutUsQuoteSlice
  | AboutUsDescriptionSlice
  | AboutUsHeroSlice
  | HoneymoonDesignSlice
  | HoneymoonFlipbookSlice
  | TravelWhySlice
  | TravelTripsSlice
  | TravelDescriptionSlice
  | FooterSlice
  | HomeFormCtaSlice
  | HomeInstagramSlice
  | HomeTravelCarouselSlice
  | HomeCarouselSlice
  | HomeDescriptionSlice
  | HeroSlice
  | NavigationSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Tipos de viajes → trips*
 */
export interface TiposDeViajesDocumentDataViajesItem {
  /**
   * trip field in *Tipos de viajes → trips*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.viajes[].trip
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  trip: prismic.ContentRelationshipField<"viajes">;
}

/**
 * Content for Tipos de viajes documents
 */
interface TiposDeViajesDocumentData {
  /**
   * title field in *Tipos de viajes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * image field in *Tipos de viajes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * punchline field in *Tipos de viajes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.punchline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  punchline: prismic.RichTextField;

  /**
   * description field in *Tipos de viajes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * trips field in *Tipos de viajes*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.viajes[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  viajes: prismic.GroupField<Simplify<TiposDeViajesDocumentDataViajesItem>>;

  /**
   * cta field in *Tipos de viajes*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;
}

/**
 * Tipos de viajes document from Prismic
 *
 * - **API ID**: `tipos_de_viajes`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TiposDeViajesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TiposDeViajesDocumentData>,
    "tipos_de_viajes",
    Lang
  >;

/**
 * Item in *Viaje → options*
 */
export interface ViajesDocumentDataOptionsItem {
  /**
   * label field in *Viaje → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: viajes.options[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * price field in *Viaje → options*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 500
   * - **API ID Path**: viajes.options[].price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;
}

/**
 * Content for Viaje documents
 */
interface ViajesDocumentData {
  /**
   * title field in *Viaje*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: viajes.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * label field in *Viaje*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: viajes.label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * image field in *Viaje*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: viajes.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * min budget field in *Viaje*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 2500
   * - **API ID Path**: viajes.min_budget
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  min_budget: prismic.NumberField;

  /**
   * max budget field in *Viaje*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 50000
   * - **API ID Path**: viajes.max_budget
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  max_budget: prismic.NumberField;

  /**
   * options field in *Viaje*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: viajes.options[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  options: prismic.GroupField<Simplify<ViajesDocumentDataOptionsItem>>;
}

/**
 * Viaje document from Prismic
 *
 * - **API ID**: `viajes`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ViajesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ViajesDocumentData>, "viajes", Lang>;

export type AllDocumentTypes =
  | PageDocument
  | TiposDeViajesDocument
  | ViajesDocument;

/**
 * Primary content in *AboutUsDescription → Default → Primary*
 */
export interface AboutUsDescriptionSliceDefaultPrimary {
  /**
   * title field in *AboutUsDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_description.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AboutUsDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_description.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *AboutUsDescription → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_description.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * first image field in *AboutUsDescription → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_description.default.primary.first_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  first_image: prismic.ImageField<never>;

  /**
   * second image field in *AboutUsDescription → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_description.default.primary.second_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  second_image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutUsDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUsDescription*
 */
type AboutUsDescriptionSliceVariation = AboutUsDescriptionSliceDefault;

/**
 * AboutUsDescription Shared Slice
 *
 * - **API ID**: `about_us_description`
 * - **Description**: AboutUsDescription
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsDescriptionSlice = prismic.SharedSlice<
  "about_us_description",
  AboutUsDescriptionSliceVariation
>;

/**
 * Primary content in *AboutUsHero → Default → Primary*
 */
export interface AboutUsHeroSliceDefaultPrimary {
  /**
   * title field in *AboutUsHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AboutUsHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for AboutUsHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUsHero*
 */
type AboutUsHeroSliceVariation = AboutUsHeroSliceDefault;

/**
 * AboutUsHero Shared Slice
 *
 * - **API ID**: `about_us_hero`
 * - **Description**: AboutUsHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsHeroSlice = prismic.SharedSlice<
  "about_us_hero",
  AboutUsHeroSliceVariation
>;

/**
 * Item in *AboutUsPress → Default → Primary → press notes*
 */
export interface AboutUsPressSliceDefaultPrimaryPressNotesItem {
  /**
   * logo field in *AboutUsPress → Default → Primary → press notes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_press.default.primary.press_notes[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * description field in *AboutUsPress → Default → Primary → press notes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_press.default.primary.press_notes[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *AboutUsPress → Default → Primary → press notes*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_press.default.primary.press_notes[].cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;
}

/**
 * Primary content in *AboutUsPress → Default → Primary*
 */
export interface AboutUsPressSliceDefaultPrimary {
  /**
   * title field in *AboutUsPress → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_press.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AboutUsPress → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_press.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * press notes field in *AboutUsPress → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_press.default.primary.press_notes[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  press_notes: prismic.GroupField<
    Simplify<AboutUsPressSliceDefaultPrimaryPressNotesItem>
  >;
}

/**
 * Default variation for AboutUsPress Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsPressSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsPressSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUsPress*
 */
type AboutUsPressSliceVariation = AboutUsPressSliceDefault;

/**
 * AboutUsPress Shared Slice
 *
 * - **API ID**: `about_us_press`
 * - **Description**: AboutUsPress
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsPressSlice = prismic.SharedSlice<
  "about_us_press",
  AboutUsPressSliceVariation
>;

/**
 * Primary content in *AboutUsQuote → Default → Primary*
 */
export interface AboutUsQuoteSliceDefaultPrimary {
  /**
   * title field in *AboutUsQuote → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_quote.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for AboutUsQuote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsQuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsQuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUsQuote*
 */
type AboutUsQuoteSliceVariation = AboutUsQuoteSliceDefault;

/**
 * AboutUsQuote Shared Slice
 *
 * - **API ID**: `about_us_quote`
 * - **Description**: AboutUsQuote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsQuoteSlice = prismic.SharedSlice<
  "about_us_quote",
  AboutUsQuoteSliceVariation
>;

/**
 * Item in *AboutUsTestimonials → Default → Primary → testimonials*
 */
export interface AboutUsTestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * rating field in *AboutUsTestimonials → Default → Primary → testimonials*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_testimonials.default.primary.testimonials[].rating
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rating: prismic.NumberField;

  /**
   * description field in *AboutUsTestimonials → Default → Primary → testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_testimonials.default.primary.testimonials[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AboutUsTestimonials → Default → Primary*
 */
export interface AboutUsTestimonialsSliceDefaultPrimary {
  /**
   * title field in *AboutUsTestimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * testimonials field in *AboutUsTestimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<AboutUsTestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for AboutUsTestimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsTestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsTestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUsTestimonials*
 */
type AboutUsTestimonialsSliceVariation = AboutUsTestimonialsSliceDefault;

/**
 * AboutUsTestimonials Shared Slice
 *
 * - **API ID**: `about_us_testimonials`
 * - **Description**: AboutUsTestimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsTestimonialsSlice = prismic.SharedSlice<
  "about_us_testimonials",
  AboutUsTestimonialsSliceVariation
>;

/**
 * Primary content in *AboutUsValues → Default → Primary*
 */
export interface AboutUsValuesSliceDefaultPrimary {
  /**
   * title field in *AboutUsValues → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_values.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AboutUsValues → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_values.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AboutUsValues → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_values.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutUsValues Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsValuesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsValuesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUsValues*
 */
type AboutUsValuesSliceVariation = AboutUsValuesSliceDefault;

/**
 * AboutUsValues Shared Slice
 *
 * - **API ID**: `about_us_values`
 * - **Description**: AboutUsValues
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsValuesSlice = prismic.SharedSlice<
  "about_us_values",
  AboutUsValuesSliceVariation
>;

/**
 * Item in *ContactForm → Default → Primary → type of trip*
 */
export interface ContactFormSliceDefaultPrimaryTypeOfTripItem {}

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * background image field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * trips field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.trips
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  trips: prismic.ContentRelationshipField<"viajes">;

  /**
   * type of trip field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.type_of_trip[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  type_of_trip: prismic.GroupField<
    Simplify<ContactFormSliceDefaultPrimaryTypeOfTripItem>
  >;

  /**
   * privacy policy pdf field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.privacy_policy_pdf
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy_policy_pdf: prismic.LinkToMediaField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → logos*
 */
export interface FooterSliceDefaultPrimaryLogosItem {
  /**
   * logo field in *Footer → Default → Primary → logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * logos field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryLogosItem>>;

  /**
   * logo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * disclaimer field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.disclaimer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  disclaimer: prismic.RichTextField;

  /**
   * address field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cta field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * background field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background: prismic.LinkToMediaField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *HomeCarousel → Default → Primary → carousel*
 */
export interface HomeCarouselSliceDefaultPrimaryCarouselItem {
  /**
   * image field in *HomeCarousel → Default → Primary → carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeCarousel → Default → Primary*
 */
export interface HomeCarouselSliceDefaultPrimary {
  /**
   * title field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * cta field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * carousel field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<HomeCarouselSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for HomeCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeCarousel*
 */
type HomeCarouselSliceVariation = HomeCarouselSliceDefault;

/**
 * HomeCarousel Shared Slice
 *
 * - **API ID**: `home_carousel`
 * - **Description**: HomeCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeCarouselSlice = prismic.SharedSlice<
  "home_carousel",
  HomeCarouselSliceVariation
>;

/**
 * Item in *HomeDescription → Default → Primary → products*
 */
export interface HomeDescriptionSliceDefaultPrimaryProductsItem {
  /**
   * title field in *HomeDescription → Default → Primary → products*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cta field in *HomeDescription → Default → Primary → products*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[].cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * background field in *HomeDescription → Default → Primary → products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[].background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeDescription → Default → Primary*
 */
export interface HomeDescriptionSliceDefaultPrimary {
  /**
   * title field in *HomeDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *HomeDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * products field in *HomeDescription → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  products: prismic.GroupField<
    Simplify<HomeDescriptionSliceDefaultPrimaryProductsItem>
  >;
}

/**
 * Default variation for HomeDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeDescription*
 */
type HomeDescriptionSliceVariation = HomeDescriptionSliceDefault;

/**
 * HomeDescription Shared Slice
 *
 * - **API ID**: `home_description`
 * - **Description**: HomeDescription
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeDescriptionSlice = prismic.SharedSlice<
  "home_description",
  HomeDescriptionSliceVariation
>;

/**
 * Primary content in *HomeFormCta → Default → Primary*
 */
export interface HomeFormCtaSliceDefaultPrimary {
  /**
   * title field in *HomeFormCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_form_cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *HomeFormCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_form_cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *HomeFormCta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_form_cta.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;
}

/**
 * Default variation for HomeFormCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeFormCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeFormCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeFormCta*
 */
type HomeFormCtaSliceVariation = HomeFormCtaSliceDefault;

/**
 * HomeFormCta Shared Slice
 *
 * - **API ID**: `home_form_cta`
 * - **Description**: HomeFormCta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeFormCtaSlice = prismic.SharedSlice<
  "home_form_cta",
  HomeFormCtaSliceVariation
>;

/**
 * Item in *HomeInstagram → Default → Primary → instagram*
 */
export interface HomeInstagramSliceDefaultPrimaryInstagramItem {
  /**
   * instagram post code field in *HomeInstagram → Default → Primary → instagram*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.instagram[].instagram_post_code
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram_post_code: prismic.KeyTextField;
}

/**
 * Item in *HomeInstagram → Default → Primary → social media*
 */
export interface HomeInstagramSliceDefaultPrimarySocialMediaItem {
  /**
   * logo field in *HomeInstagram → Default → Primary → social media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.social_media[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * link field in *HomeInstagram → Default → Primary → social media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.social_media[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *HomeInstagram → Default → Primary*
 */
export interface HomeInstagramSliceDefaultPrimary {
  /**
   * title field in *HomeInstagram → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * instagram field in *HomeInstagram → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.instagram[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  instagram: prismic.GroupField<
    Simplify<HomeInstagramSliceDefaultPrimaryInstagramItem>
  >;

  /**
   * social media field in *HomeInstagram → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.social_media[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<
    Simplify<HomeInstagramSliceDefaultPrimarySocialMediaItem>
  >;
}

/**
 * Default variation for HomeInstagram Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeInstagramSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeInstagramSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeInstagram*
 */
type HomeInstagramSliceVariation = HomeInstagramSliceDefault;

/**
 * HomeInstagram Shared Slice
 *
 * - **API ID**: `home_instagram`
 * - **Description**: HomeInstagram
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeInstagramSlice = prismic.SharedSlice<
  "home_instagram",
  HomeInstagramSliceVariation
>;

/**
 * Item in *HomeTravelCarousel → Default → Primary → carousel*
 */
export interface HomeTravelCarouselSliceDefaultPrimaryCarouselItem {
  /**
   * image field in *HomeTravelCarousel → Default → Primary → carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeTravelCarousel → Default → Primary*
 */
export interface HomeTravelCarouselSliceDefaultPrimary {
  /**
   * title field in *HomeTravelCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cta field in *HomeTravelCarousel → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * carousel field in *HomeTravelCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<HomeTravelCarouselSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for HomeTravelCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeTravelCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeTravelCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeTravelCarousel*
 */
type HomeTravelCarouselSliceVariation = HomeTravelCarouselSliceDefault;

/**
 * HomeTravelCarousel Shared Slice
 *
 * - **API ID**: `home_travel_carousel`
 * - **Description**: HomeTravelCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeTravelCarouselSlice = prismic.SharedSlice<
  "home_travel_carousel",
  HomeTravelCarouselSliceVariation
>;

/**
 * Item in *HoneymoonDesign → Default → Primary → items*
 */
export interface HoneymoonDesignSliceDefaultPrimaryItemsItem {
  /**
   * title field in *HoneymoonDesign → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: honeymoon_design.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *HoneymoonDesign → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: honeymoon_design.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *HoneymoonDesign → Default → Primary*
 */
export interface HoneymoonDesignSliceDefaultPrimary {
  /**
   * title field in *HoneymoonDesign → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: honeymoon_design.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *HoneymoonDesign → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: honeymoon_design.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *HoneymoonDesign → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: honeymoon_design.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * items field in *HoneymoonDesign → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: honeymoon_design.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<HoneymoonDesignSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for HoneymoonDesign Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HoneymoonDesignSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HoneymoonDesignSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HoneymoonDesign*
 */
type HoneymoonDesignSliceVariation = HoneymoonDesignSliceDefault;

/**
 * HoneymoonDesign Shared Slice
 *
 * - **API ID**: `honeymoon_design`
 * - **Description**: HoneymoonDesign
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HoneymoonDesignSlice = prismic.SharedSlice<
  "honeymoon_design",
  HoneymoonDesignSliceVariation
>;

/**
 * Primary content in *HoneymoonFlipbook → Default → Primary*
 */
export interface HoneymoonFlipbookSliceDefaultPrimary {
  /**
   * pdf field in *HoneymoonFlipbook → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: honeymoon_flipbook.default.primary.pdf
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  pdf: prismic.LinkToMediaField;
}

/**
 * Default variation for HoneymoonFlipbook Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HoneymoonFlipbookSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HoneymoonFlipbookSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HoneymoonFlipbook*
 */
type HoneymoonFlipbookSliceVariation = HoneymoonFlipbookSliceDefault;

/**
 * HoneymoonFlipbook Shared Slice
 *
 * - **API ID**: `honeymoon_flipbook`
 * - **Description**: HoneymoonFlipbook
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HoneymoonFlipbookSlice = prismic.SharedSlice<
  "honeymoon_flipbook",
  HoneymoonFlipbookSliceVariation
>;

/**
 * Item in *Navigation → Default → Primary → navigation item*
 */
export interface NavigationSliceDefaultPrimaryNavigationItemItem {
  /**
   * image field in *Navigation → Default → Primary → navigation item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.navigation_item[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *Navigation → Default → Primary → navigation item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.navigation_item[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Navigation → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
  /**
   * navigation item field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.navigation_item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_item: prismic.GroupField<
    Simplify<NavigationSliceDefaultPrimaryNavigationItemItem>
  >;

  /**
   * mobile cta field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.mobile_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mobile_cta: prismic.LinkField;

  /**
   * forced color field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.forced_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  forced_color: prismic.ColorField;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault;

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlice = prismic.SharedSlice<
  "navigation",
  NavigationSliceVariation
>;

/**
 * Primary content in *TravelDescription → Default → Primary*
 */
export interface TravelDescriptionSliceDefaultPrimary {
  /**
   * title field in *TravelDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_description.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *TravelDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_description.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *TravelDescription → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_description.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;
}

/**
 * Default variation for TravelDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TravelDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TravelDescription*
 */
type TravelDescriptionSliceVariation = TravelDescriptionSliceDefault;

/**
 * TravelDescription Shared Slice
 *
 * - **API ID**: `travel_description`
 * - **Description**: TravelDescription
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelDescriptionSlice = prismic.SharedSlice<
  "travel_description",
  TravelDescriptionSliceVariation
>;

/**
 * Item in *TravelTrips → Default → Primary → trips types*
 */
export interface TravelTripsSliceDefaultPrimaryTripsTypesItem {
  /**
   * trip types field in *TravelTrips → Default → Primary → trips types*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_trips.default.primary.trips_types[].trip_types
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  trip_types: prismic.ContentRelationshipField<"tipos_de_viajes">;
}

/**
 * Primary content in *TravelTrips → Default → Primary*
 */
export interface TravelTripsSliceDefaultPrimary {
  /**
   * trips types field in *TravelTrips → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_trips.default.primary.trips_types[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  trips_types: prismic.GroupField<
    Simplify<TravelTripsSliceDefaultPrimaryTripsTypesItem>
  >;
}

/**
 * Default variation for TravelTrips Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelTripsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TravelTripsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TravelTrips*
 */
type TravelTripsSliceVariation = TravelTripsSliceDefault;

/**
 * TravelTrips Shared Slice
 *
 * - **API ID**: `travel_trips`
 * - **Description**: TravelTrips
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelTripsSlice = prismic.SharedSlice<
  "travel_trips",
  TravelTripsSliceVariation
>;

/**
 * Item in *TravelWhy → Default → Primary → items*
 */
export interface TravelWhySliceDefaultPrimaryItemsItem {
  /**
   * description field in *TravelWhy → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_why.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *TravelWhy → Default → Primary*
 */
export interface TravelWhySliceDefaultPrimary {
  /**
   * title field in *TravelWhy → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_why.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *TravelWhy → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_why.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *TravelWhy → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_why.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * items field in *TravelWhy → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_why.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<TravelWhySliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for TravelWhy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelWhySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TravelWhySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TravelWhy*
 */
type TravelWhySliceVariation = TravelWhySliceDefault;

/**
 * TravelWhy Shared Slice
 *
 * - **API ID**: `travel_why`
 * - **Description**: TravelWhy
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelWhySlice = prismic.SharedSlice<
  "travel_why",
  TravelWhySliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      TiposDeViajesDocument,
      TiposDeViajesDocumentData,
      TiposDeViajesDocumentDataViajesItem,
      ViajesDocument,
      ViajesDocumentData,
      ViajesDocumentDataOptionsItem,
      AllDocumentTypes,
      AboutUsDescriptionSlice,
      AboutUsDescriptionSliceDefaultPrimary,
      AboutUsDescriptionSliceVariation,
      AboutUsDescriptionSliceDefault,
      AboutUsHeroSlice,
      AboutUsHeroSliceDefaultPrimary,
      AboutUsHeroSliceVariation,
      AboutUsHeroSliceDefault,
      AboutUsPressSlice,
      AboutUsPressSliceDefaultPrimaryPressNotesItem,
      AboutUsPressSliceDefaultPrimary,
      AboutUsPressSliceVariation,
      AboutUsPressSliceDefault,
      AboutUsQuoteSlice,
      AboutUsQuoteSliceDefaultPrimary,
      AboutUsQuoteSliceVariation,
      AboutUsQuoteSliceDefault,
      AboutUsTestimonialsSlice,
      AboutUsTestimonialsSliceDefaultPrimaryTestimonialsItem,
      AboutUsTestimonialsSliceDefaultPrimary,
      AboutUsTestimonialsSliceVariation,
      AboutUsTestimonialsSliceDefault,
      AboutUsValuesSlice,
      AboutUsValuesSliceDefaultPrimary,
      AboutUsValuesSliceVariation,
      AboutUsValuesSliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimaryTypeOfTripItem,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimaryLogosItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HomeCarouselSlice,
      HomeCarouselSliceDefaultPrimaryCarouselItem,
      HomeCarouselSliceDefaultPrimary,
      HomeCarouselSliceVariation,
      HomeCarouselSliceDefault,
      HomeDescriptionSlice,
      HomeDescriptionSliceDefaultPrimaryProductsItem,
      HomeDescriptionSliceDefaultPrimary,
      HomeDescriptionSliceVariation,
      HomeDescriptionSliceDefault,
      HomeFormCtaSlice,
      HomeFormCtaSliceDefaultPrimary,
      HomeFormCtaSliceVariation,
      HomeFormCtaSliceDefault,
      HomeInstagramSlice,
      HomeInstagramSliceDefaultPrimaryInstagramItem,
      HomeInstagramSliceDefaultPrimarySocialMediaItem,
      HomeInstagramSliceDefaultPrimary,
      HomeInstagramSliceVariation,
      HomeInstagramSliceDefault,
      HomeTravelCarouselSlice,
      HomeTravelCarouselSliceDefaultPrimaryCarouselItem,
      HomeTravelCarouselSliceDefaultPrimary,
      HomeTravelCarouselSliceVariation,
      HomeTravelCarouselSliceDefault,
      HoneymoonDesignSlice,
      HoneymoonDesignSliceDefaultPrimaryItemsItem,
      HoneymoonDesignSliceDefaultPrimary,
      HoneymoonDesignSliceVariation,
      HoneymoonDesignSliceDefault,
      HoneymoonFlipbookSlice,
      HoneymoonFlipbookSliceDefaultPrimary,
      HoneymoonFlipbookSliceVariation,
      HoneymoonFlipbookSliceDefault,
      NavigationSlice,
      NavigationSliceDefaultPrimaryNavigationItemItem,
      NavigationSliceDefaultPrimary,
      NavigationSliceVariation,
      NavigationSliceDefault,
      TravelDescriptionSlice,
      TravelDescriptionSliceDefaultPrimary,
      TravelDescriptionSliceVariation,
      TravelDescriptionSliceDefault,
      TravelTripsSlice,
      TravelTripsSliceDefaultPrimaryTripsTypesItem,
      TravelTripsSliceDefaultPrimary,
      TravelTripsSliceVariation,
      TravelTripsSliceDefault,
      TravelWhySlice,
      TravelWhySliceDefaultPrimaryItemsItem,
      TravelWhySliceDefaultPrimary,
      TravelWhySliceVariation,
      TravelWhySliceDefault,
    };
  }
}
