// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | TravelTripsSlice
  | TravelDescriptionSlice
  | FooterSlice
  | HomeFormCtaSlice
  | HomeInstagramSlice
  | HomeTravelCarouselSlice
  | HomeCarouselSlice
  | HomeDescriptionSlice
  | HeroSlice
  | NavigationSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Tipos de viajes → trips*
 */
export interface TiposDeViajesDocumentDataViajesItem {
  /**
   * trip field in *Tipos de viajes → trips*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.viajes[].trip
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  trip: prismic.ContentRelationshipField<"viajes">;
}

/**
 * Content for Tipos de viajes documents
 */
interface TiposDeViajesDocumentData {
  /**
   * title field in *Tipos de viajes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * image field in *Tipos de viajes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * punchline field in *Tipos de viajes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.punchline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  punchline: prismic.RichTextField;

  /**
   * description field in *Tipos de viajes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * trips field in *Tipos de viajes*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.viajes[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  viajes: prismic.GroupField<Simplify<TiposDeViajesDocumentDataViajesItem>>;

  /**
   * cta field in *Tipos de viajes*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tipos_de_viajes.cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;
}

/**
 * Tipos de viajes document from Prismic
 *
 * - **API ID**: `tipos_de_viajes`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TiposDeViajesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TiposDeViajesDocumentData>,
    "tipos_de_viajes",
    Lang
  >;

/**
 * Content for Viaje documents
 */
interface ViajesDocumentData {
  /**
   * title field in *Viaje*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: viajes.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * image field in *Viaje*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: viajes.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Viaje document from Prismic
 *
 * - **API ID**: `viajes`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ViajesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ViajesDocumentData>, "viajes", Lang>;

export type AllDocumentTypes =
  | PageDocument
  | TiposDeViajesDocument
  | ViajesDocument;

/**
 * Item in *Footer → Default → Primary → logos*
 */
export interface FooterSliceDefaultPrimaryLogosItem {
  /**
   * logo field in *Footer → Default → Primary → logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * logos field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryLogosItem>>;

  /**
   * logo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * disclaimer field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.disclaimer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  disclaimer: prismic.RichTextField;

  /**
   * address field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cta field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * background field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background: prismic.LinkToMediaField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *HomeCarousel → Default → Primary → carousel*
 */
export interface HomeCarouselSliceDefaultPrimaryCarouselItem {
  /**
   * image field in *HomeCarousel → Default → Primary → carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeCarousel → Default → Primary*
 */
export interface HomeCarouselSliceDefaultPrimary {
  /**
   * title field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * cta field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * carousel field in *HomeCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_carousel.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<HomeCarouselSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for HomeCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeCarousel*
 */
type HomeCarouselSliceVariation = HomeCarouselSliceDefault;

/**
 * HomeCarousel Shared Slice
 *
 * - **API ID**: `home_carousel`
 * - **Description**: HomeCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeCarouselSlice = prismic.SharedSlice<
  "home_carousel",
  HomeCarouselSliceVariation
>;

/**
 * Item in *HomeDescription → Default → Primary → products*
 */
export interface HomeDescriptionSliceDefaultPrimaryProductsItem {
  /**
   * title field in *HomeDescription → Default → Primary → products*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cta field in *HomeDescription → Default → Primary → products*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[].cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * background field in *HomeDescription → Default → Primary → products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[].background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeDescription → Default → Primary*
 */
export interface HomeDescriptionSliceDefaultPrimary {
  /**
   * title field in *HomeDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *HomeDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * products field in *HomeDescription → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_description.default.primary.products[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  products: prismic.GroupField<
    Simplify<HomeDescriptionSliceDefaultPrimaryProductsItem>
  >;
}

/**
 * Default variation for HomeDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeDescription*
 */
type HomeDescriptionSliceVariation = HomeDescriptionSliceDefault;

/**
 * HomeDescription Shared Slice
 *
 * - **API ID**: `home_description`
 * - **Description**: HomeDescription
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeDescriptionSlice = prismic.SharedSlice<
  "home_description",
  HomeDescriptionSliceVariation
>;

/**
 * Primary content in *HomeFormCta → Default → Primary*
 */
export interface HomeFormCtaSliceDefaultPrimary {
  /**
   * title field in *HomeFormCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_form_cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *HomeFormCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_form_cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *HomeFormCta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_form_cta.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;
}

/**
 * Default variation for HomeFormCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeFormCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeFormCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeFormCta*
 */
type HomeFormCtaSliceVariation = HomeFormCtaSliceDefault;

/**
 * HomeFormCta Shared Slice
 *
 * - **API ID**: `home_form_cta`
 * - **Description**: HomeFormCta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeFormCtaSlice = prismic.SharedSlice<
  "home_form_cta",
  HomeFormCtaSliceVariation
>;

/**
 * Item in *HomeInstagram → Default → Primary → instagram*
 */
export interface HomeInstagramSliceDefaultPrimaryInstagramItem {
  /**
   * instagram post code field in *HomeInstagram → Default → Primary → instagram*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.instagram[].instagram_post_code
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram_post_code: prismic.KeyTextField;
}

/**
 * Item in *HomeInstagram → Default → Primary → social media*
 */
export interface HomeInstagramSliceDefaultPrimarySocialMediaItem {
  /**
   * logo field in *HomeInstagram → Default → Primary → social media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.social_media[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * link field in *HomeInstagram → Default → Primary → social media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.social_media[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *HomeInstagram → Default → Primary*
 */
export interface HomeInstagramSliceDefaultPrimary {
  /**
   * title field in *HomeInstagram → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * instagram field in *HomeInstagram → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.instagram[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  instagram: prismic.GroupField<
    Simplify<HomeInstagramSliceDefaultPrimaryInstagramItem>
  >;

  /**
   * social media field in *HomeInstagram → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_instagram.default.primary.social_media[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<
    Simplify<HomeInstagramSliceDefaultPrimarySocialMediaItem>
  >;
}

/**
 * Default variation for HomeInstagram Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeInstagramSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeInstagramSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeInstagram*
 */
type HomeInstagramSliceVariation = HomeInstagramSliceDefault;

/**
 * HomeInstagram Shared Slice
 *
 * - **API ID**: `home_instagram`
 * - **Description**: HomeInstagram
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeInstagramSlice = prismic.SharedSlice<
  "home_instagram",
  HomeInstagramSliceVariation
>;

/**
 * Item in *HomeTravelCarousel → Default → Primary → carousel*
 */
export interface HomeTravelCarouselSliceDefaultPrimaryCarouselItem {
  /**
   * image field in *HomeTravelCarousel → Default → Primary → carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeTravelCarousel → Default → Primary*
 */
export interface HomeTravelCarouselSliceDefaultPrimary {
  /**
   * title field in *HomeTravelCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * cta field in *HomeTravelCarousel → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;

  /**
   * carousel field in *HomeTravelCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_travel_carousel.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<HomeTravelCarouselSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for HomeTravelCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeTravelCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeTravelCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeTravelCarousel*
 */
type HomeTravelCarouselSliceVariation = HomeTravelCarouselSliceDefault;

/**
 * HomeTravelCarousel Shared Slice
 *
 * - **API ID**: `home_travel_carousel`
 * - **Description**: HomeTravelCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeTravelCarouselSlice = prismic.SharedSlice<
  "home_travel_carousel",
  HomeTravelCarouselSliceVariation
>;

/**
 * Item in *Navigation → Default → Primary → navigation item*
 */
export interface NavigationSliceDefaultPrimaryNavigationItemItem {
  /**
   * image field in *Navigation → Default → Primary → navigation item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.navigation_item[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *Navigation → Default → Primary → navigation item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.navigation_item[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Navigation → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
  /**
   * navigation item field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.navigation_item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_item: prismic.GroupField<
    Simplify<NavigationSliceDefaultPrimaryNavigationItemItem>
  >;

  /**
   * mobile cta field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.mobile_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mobile_cta: prismic.LinkField;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault;

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlice = prismic.SharedSlice<
  "navigation",
  NavigationSliceVariation
>;

/**
 * Primary content in *TravelDescription → Default → Primary*
 */
export interface TravelDescriptionSliceDefaultPrimary {
  /**
   * title field in *TravelDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_description.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *TravelDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_description.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta field in *TravelDescription → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_description.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;
}

/**
 * Default variation for TravelDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TravelDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TravelDescription*
 */
type TravelDescriptionSliceVariation = TravelDescriptionSliceDefault;

/**
 * TravelDescription Shared Slice
 *
 * - **API ID**: `travel_description`
 * - **Description**: TravelDescription
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelDescriptionSlice = prismic.SharedSlice<
  "travel_description",
  TravelDescriptionSliceVariation
>;

/**
 * Item in *TravelTrips → Default → Primary → trips types*
 */
export interface TravelTripsSliceDefaultPrimaryTripsTypesItem {
  /**
   * trip types field in *TravelTrips → Default → Primary → trips types*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_trips.default.primary.trips_types[].trip_types
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  trip_types: prismic.ContentRelationshipField<"tipos_de_viajes">;
}

/**
 * Primary content in *TravelTrips → Default → Primary*
 */
export interface TravelTripsSliceDefaultPrimary {
  /**
   * trips types field in *TravelTrips → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_trips.default.primary.trips_types[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  trips_types: prismic.GroupField<
    Simplify<TravelTripsSliceDefaultPrimaryTripsTypesItem>
  >;
}

/**
 * Default variation for TravelTrips Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelTripsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TravelTripsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TravelTrips*
 */
type TravelTripsSliceVariation = TravelTripsSliceDefault;

/**
 * TravelTrips Shared Slice
 *
 * - **API ID**: `travel_trips`
 * - **Description**: TravelTrips
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelTripsSlice = prismic.SharedSlice<
  "travel_trips",
  TravelTripsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      TiposDeViajesDocument,
      TiposDeViajesDocumentData,
      TiposDeViajesDocumentDataViajesItem,
      ViajesDocument,
      ViajesDocumentData,
      AllDocumentTypes,
      FooterSlice,
      FooterSliceDefaultPrimaryLogosItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HomeCarouselSlice,
      HomeCarouselSliceDefaultPrimaryCarouselItem,
      HomeCarouselSliceDefaultPrimary,
      HomeCarouselSliceVariation,
      HomeCarouselSliceDefault,
      HomeDescriptionSlice,
      HomeDescriptionSliceDefaultPrimaryProductsItem,
      HomeDescriptionSliceDefaultPrimary,
      HomeDescriptionSliceVariation,
      HomeDescriptionSliceDefault,
      HomeFormCtaSlice,
      HomeFormCtaSliceDefaultPrimary,
      HomeFormCtaSliceVariation,
      HomeFormCtaSliceDefault,
      HomeInstagramSlice,
      HomeInstagramSliceDefaultPrimaryInstagramItem,
      HomeInstagramSliceDefaultPrimarySocialMediaItem,
      HomeInstagramSliceDefaultPrimary,
      HomeInstagramSliceVariation,
      HomeInstagramSliceDefault,
      HomeTravelCarouselSlice,
      HomeTravelCarouselSliceDefaultPrimaryCarouselItem,
      HomeTravelCarouselSliceDefaultPrimary,
      HomeTravelCarouselSliceVariation,
      HomeTravelCarouselSliceDefault,
      NavigationSlice,
      NavigationSliceDefaultPrimaryNavigationItemItem,
      NavigationSliceDefaultPrimary,
      NavigationSliceVariation,
      NavigationSliceDefault,
      TravelDescriptionSlice,
      TravelDescriptionSliceDefaultPrimary,
      TravelDescriptionSliceVariation,
      TravelDescriptionSliceDefault,
      TravelTripsSlice,
      TravelTripsSliceDefaultPrimaryTripsTypesItem,
      TravelTripsSliceDefaultPrimary,
      TravelTripsSliceVariation,
      TravelTripsSliceDefault,
    };
  }
}
