// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us_description: dynamic(() => import("./AboutUsDescription")),
  about_us_hero: dynamic(() => import("./AboutUsHero")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  home_carousel: dynamic(() => import("./HomeCarousel")),
  home_description: dynamic(() => import("./HomeDescription")),
  home_form_cta: dynamic(() => import("./HomeFormCta")),
  home_instagram: dynamic(() => import("./HomeInstagram")),
  home_travel_carousel: dynamic(() => import("./HomeTravelCarousel")),
  honeymoon_design: dynamic(() => import("./HoneymoonDesign")),
  honeymoon_flipbook: dynamic(() => import("./HoneymoonFlipbook")),
  navigation: dynamic(() => import("./Navigation")),
  travel_description: dynamic(() => import("./TravelDescription")),
  travel_trips: dynamic(() => import("./TravelTrips")),
  travel_why: dynamic(() => import("./TravelWhy")),
};
